#include "RippedPages.h"

#include <iostream>

void RippedPages::printRippedPageContents(int locationNum, int pageNum) {
    std::cout << "-------------------" << std::endl;
    std::cout << "Ripped Page "  << pageNum << std::endl;
    std::cout << "-------------------" << std::endl;
    switch(locationNum) {
        case 1:     // Guest Bedroom
            std::cout << "I’ve been working on this job for around 2 days. This is taking a little longer than expected as this house is a lot bigger than I had imagined. In addition, the house was trashed, so it was a lot harder to move around the area. I mean it makes sense why they sent me this job in the first place but why didn’t they call me sooner. This house looks like it was abandoned for quite a while. My best guess is that it would've been abandoned for around 6 months to a year. Everything was dusty but not many things looked broken down yet. This job is actually not as bad as I thought, I had some peace and quiet. It was quite a break from city life I can tell you that. Anyways, I need to get back to work. I’m almost done so hopefully I can get back home soon." << std::endl;
            break;
        case 2:     // Guest Bathroom
            std::cout << "Oh god, I don’t know what to do right now. I had some problems accessing certain areas of the house so I called them for help. They ended up sending me 1 person to help me. He was a nice guy, name was John, and he helped me solve the problem in 9 hours. But the problem was that when he went to leave, he was unable to open the front door. We tried pushing through the door but it wasn’t budging. It was like it sealed off to keep us in. We tried the windows but they felt like they were glued shut and they were also boarded up which was really weird. How did someone do all of this without us hearing or noticing anything? Although, there was one weird thing that had happened. We heard a distant roar while we were working followed by rapid noises surrounding the house. We were alarmed but figured it was due to the high winds. In terms of escaping, we tried everything but were unable to do anything. The good thing was that he brought some fresh food for us to eat. Right now, we’re camped in the master bedroom preparing to stay the night. In the morning, we’re going to think about how we’re going to escape this place." << std::endl;
            break;
        case 3:     // Living Room
            std::cout << "I’ve been feeling really guilty lately that I haven’t been able to financially support my family enough. My wife already has her hands full taking care of our 3 kids so it’s my job to support them as much as I can. I’ve been working multiple jobs in order to survive. I’m hoping that this job will give us the boost that we need to live a little more comfortably. I’m heading out to the job in a little over a week. 8 days to be exact. I’m trying my best here but I feel like everything that I’m doing is always not enough. I need to figure out some way to make more money to comfortably support our family." << std::endl;
            break;
        case 4:     // Kitchen
            std::cout << "It’s been 5 days since I’ve been able to write here. I lost my notebook due to the monster roaming the house. I don’t have much time, the monster had already taken John. It didn’t look like he had much of a chance of surviving. The monster had large teeth, and many of them. It had an absurd amount of little arm-like limbs coming out from its stomach. It was thin and fast and their legs were so long it could reach across the entire room. The monster grabbed him by the head and crawled out of the room to some other location, I have no idea. I managed to hide from it but I think it’s going to come back. I don’t think I can leave the room, I think it can sense my movements. I’m afraid to move. I’m so scared. I can’t think straight. All I can think about is my family at home. What will they think if I never come home? I’m trying to be positive but to be realistic, there’s almost a 0 percent chance of surviving this. I will try my best to sneak out. Maybe I can sneak out when it’s feasting on its next victim. I don’t have much of a shot but I think I got this. If anyone finds this, please tell my family I love them. My name is Peter Smith. I think I hear something outside the door. I need to st~~~~~" << std::endl;
            break;
        case 5:     // Dining Room
            std::cout << "I finally got a new job today. I was tasked to go to this house located down in the woods to shut off some utility. The deadline for the job is 4 weeks from now, which would be on October 7th. It’s not exactly my ideal job but I need to take what I can get. I have a family to take care of at home so any source of income is a blessing at this point. I don’t know why they gave me a job in such a remote location. They could’ve given me any other house in the city. I’m kind of dreading going to this job, but I have no choice. My circumstances are not really allowing me to be flexible in terms of jobs so I guess I have no choice." << std::endl;
            break;
        default:
            break;
    }
}

std::string RippedPages::getRippedPageContents(int pageNum) {
    switch(pageNum) {
        std::cout << "-------------------" << std::endl;
        std::cout << "Ripped Page "  << pageNum << std::endl;
        std::cout << "-------------------" << std::endl;
        case 1:
            return "I finally got a new job today. I was tasked to go to this house located down in the woods to shut off some utility. The deadline for the job is 4 weeks from now, which would be on October 7th. It’s not exactly my ideal job but I need to take what I can get. I have a family to take care of at home so any source of income is a blessing at this point. I don’t know why they gave me a job in such a remote location. They could’ve given me any other house in the city. I’m kind of dreading going to this job, but I have no choice. My circumstances are not really allowing me to be flexible in terms of jobs so I guess I have no choice.";
        case 16:
            return "I’ve been feeling really guilty lately that I haven’t been able to financially support my family enough. My wife already has her hands full taking care of our 3 kids so it’s my job to support them as much as I can. I’ve been working multiple jobs in order to survive. I’m hoping that this job will give us the boost that we need to live a little more comfortably. I’m heading out to the job in a little over a week. 8 days to be exact. I’m trying my best here but I feel like everything that I’m doing is always not enough. I need to figure out some way to make more money to comfortably support our family.";   
        case 26:
            return "I’ve been working on this job for around 2 days. This is taking a little longer than expected as this house is a lot bigger than I had imagined. In addition, the house was trashed, so it was a lot harder to move around the area. I mean it makes sense why they sent me this job in the first place but why didn’t they call me sooner. This house looks like it was abandoned for quite a while. My best guess is that it would've been abandoned for around 6 months to a year. Everything was dusty but not many things looked broken down yet. This job is actually not as bad as I thought, I had some peace and quiet. It was quite a break from city life I can tell you that. Anyways, I need to get back to work. I’m almost done so hopefully I can get back home soon.";
        case 30:
            return "Oh god, I don’t know what to do right now. I had some problems accessing certain areas of the house so I called them for help. They ended up sending me 1 person to help me. He was a nice guy, name was John, and he helped me solve the problem in 9 hours. But the problem was that when he went to leave, he was unable to open the front door. We tried pushing through the door but it wasn’t budging. It was like it sealed off to keep us in. We tried the windows but they felt like they were glued shut and they were also boarded up which was really weird. How did someone do all of this without us hearing or noticing anything? Although, there was one weird thing that had happened. We heard a distant roar while we were working followed by rapid noises surrounding the house. We were alarmed but figured it was due to the high winds. In terms of escaping, we tried everything but were unable to do anything. The good thing was that he brought some fresh food for us to eat. Right now, we’re camped in the master bedroom preparing to stay the night. In the morning, we’re going to think about how we’re going to escape this place.";
        case 34:
            return "It’s been 5 days since I’ve been able to write here. I lost my notebook due to the monster roaming the house. I don’t have much time, the monster had already taken John. It didn’t look like he had much of a chance of surviving. The monster had large teeth, and many of them. It had an absurd amount of little arm-like limbs coming out from its stomach. It was thin and fast and their legs were so long it could reach across the entire room. The monster grabbed him by the head and crawled out of the room to some other location, I have no idea. I managed to hide from it but I think it’s going to come back. I don’t think I can leave the room, I think it can sense my movements. I’m afraid to move. I’m so scared. I can’t think straight. All I can think about is my family at home. What will they think if I never come home? I’m trying to be positive but to be realistic, there’s almost a 0 percent chance of surviving this. I will try my best to sneak out. Maybe I can sneak out when it’s feasting on its next victim. I don’t have much of a shot but I think I got this. If anyone finds this, please tell my family I love them. My name is Peter Smith. I think I hear something outside the door. I need to st~~~~~";
        default:
            return "";
    }
}